#!/bin/bash 

### BEGIN INIT INFO
# Provides:           video-organizer
# Required-Start:     $all
# Required-Stop:   
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  collect images
### END INIT INFO

########### process files #############
                                      #
SERVICE=/opt/services                 #
                                      #
PID_FILE="/var/run/organizer.pid"     #
                                      #
PROCESS="$SERVICE/organizer.py"       #
                                      #
#######################################

# colors #

RD='\033[0;31m'
GN='\033[0;32m'
BL='\033[0;34m'
NC='\033[0m'

# get the process id #

rtn_pid() {

   cat "$PID_FILE"

}

# check if service is active #

running() {

   [ -f "$PID_FILE" ] && ps `rtn_pid` > /dev/null 2>&1

}

# run #

case "$1" in

   start)

      if running; then

         echo "service is running!"

      else

         echo "starting organizer service..."

         $PROCESS > /dev/null 2>&1 & 

         sleep 1

         echo -e "service started at ${GN}$!${NC}"

         echo $! > "$PID_FILE"

      fi

      ;;

   stop)

      if running; then 

         echo "stopping organizer service..."

         kill `rtn_pid`

         sleep 1

         echo -e "process killed at" ${RD}`rtn_pid`${NC}

         if [ -f "$PID_FILE" ]; then
         
            rm "$PID_FILE"
         
         fi

      else

         echo "not running. nothing to do"

      fi

      ;;

   status)

      if running; then

         echo -e "${BL}-- running --${NC}"

      else

         echo -e "${RD}stopped${NC}"

         exit 1

      fi 

      ;;

   *)

      echo "usage: service video-organizer {start|stop}"

      ;;

esac

exit 0

